/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface CardioSet {
  createdAt: Generated<string>;
  durationSeconds: number;
  exerciseId: number;
  id: Generated<number>;
  updatedAt: Generated<string>;
}

export interface Exercise {
  createdAt: Generated<string>;
  exerciseType: Generated<string>;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<string>;
}

export interface WeightSet {
  createdAt: Generated<string>;
  exerciseId: number;
  id: Generated<number>;
  reps: number;
  updatedAt: Generated<string>;
  weight: number;
}

export interface WorkoutExercise {
  createdAt: Generated<string>;
  exerciseId: number;
  id: Generated<number>;
  updatedAt: Generated<string>;
  workoutId: number;
}

export interface Workout {
  createdAt: Generated<string>;
  id: Generated<number>;
  name: string;
  updatedAt: Generated<string>;
}

export interface DB {
  cardioSets: CardioSet;
  exercises: Exercise;
  weightSets: WeightSet;
  workoutExercises: WorkoutExercise;
  workouts: Workout;
}
